import {
  buildUserManagementContentProps,
  buildUserManagementModalProps,
} from './userManagementPageSections';

describe('userManagementPageSections', () => {
  const page = {
    isMobile: true,
    canCreateUsers: true,
    isSubAdminUser: false,
    filteredUsers: [{ user_id: 'u-1' }],
    canManageUsers: true,
    canEditUserPolicy: true,
    canAssignGroups: true,
    canAssignTools: true,
    canResetPasswords: true,
    canResetPasswordForUser: jest.fn(),
    canToggleUserStatus: true,
    canDeleteUsers: true,
    statusUpdatingUserId: 'u-1',
    filters: { q: 'alice' },
    companies: [{ id: 1 }],
    departments: [{ id: 11 }],
    availableGroups: [{ group_id: 7 }],
    availableTools: [{ group_id: 'paper_download' }],
    assignableTools: [{ group_id: 'drug_admin' }],
    permissionGroupsLoading: true,
    permissionGroupsError: 'permission groups unavailable',
    groupedUsers: { QA: [] },
    setFilters: jest.fn(),
    handleLoadPermissionGroups: jest.fn(),
    handleOpenCreateModal: jest.fn(),
    handleOpenPolicyModal: jest.fn(),
    handleAssignGroup: jest.fn(),
    handleAssignTool: jest.fn(),
    handleOpenResetPassword: jest.fn(),
    handleDeleteUser: jest.fn(),
    handleToggleUserStatus: jest.fn(),
    handleResetFilters: jest.fn(),
    showCreateModal: true,
    allUsers: [{ user_id: 'u-10', username: 'alice' }],
    newUser: { username: 'alice' },
    createUserError: 'create error',
    editingGroupUser: { user_id: 'u-1' },
    showGroupModal: true,
    selectedGroupIds: [7],
    editingToolUser: { user_id: 'u-2' },
    showToolModal: true,
    selectedToolIds: ['paper_download'],
    showResetPasswordModal: true,
    resetPasswordUser: { user_id: 'u-1' },
    resetPasswordValue: 'Password1',
    resetPasswordConfirm: 'Password1',
    resetPasswordSubmitting: true,
    resetPasswordError: 'reset error',
    showPolicyModal: true,
    policyUser: { user_id: 'u-1' },
    policySubmitting: true,
    policyError: 'policy error',
    policyForm: { user_type: 'normal' },
    showDisableUserModal: true,
    disableTargetUser: { user_id: 'u-2' },
    disableMode: 'until',
    disableUntilDate: '2026-04-07',
    disableUserError: 'disable error',
    orgDirectoryError: 'org error',
    kbDirectoryNodes: [{ id: 'node-1' }],
    kbDirectoryLoading: true,
    kbDirectoryError: 'kb error',
    kbDirectoryCreateError: 'create kb error',
    kbDirectoryCreatingRoot: true,
    managedKbRootInvalid: true,
    subAdminOptions: [{ value: 'sub-1' }],
    policySubAdminOptions: [{ value: 'sub-2' }],
    handleChangePolicyForm: jest.fn(),
    setResetPasswordValue: jest.fn(),
    setResetPasswordConfirm: jest.fn(),
    handleCloseCreateModal: jest.fn(),
    setNewUserField: jest.fn(),
    toggleNewUserGroup: jest.fn(),
    toggleNewUserTool: jest.fn(),
    handleCreateUser: jest.fn(),
    handleCloseResetPassword: jest.fn(),
    handleSubmitResetPassword: jest.fn(),
    handleClosePolicyModal: jest.fn(),
    handleTogglePolicyGroup: jest.fn(),
    handleTogglePolicyTool: jest.fn(),
    handleSavePolicy: jest.fn(),
    handleCloseDisableUserModal: jest.fn(),
    handleChangeDisableMode: jest.fn(),
    handleChangeDisableUntilDate: jest.fn(),
    handleConfirmDisableUser: jest.fn(),
    handleCloseGroupModal: jest.fn(),
    toggleSelectedGroup: jest.fn(),
    handleSaveGroup: jest.fn(),
    handleCloseToolModal: jest.fn(),
    toggleSelectedTool: jest.fn(),
    handleSaveTool: jest.fn(),
    handleCreateModalRootDirectory: jest.fn(),
    handlePolicyRootDirectory: jest.fn(),
    unrelatedValue: 'ignore me',
  };

  it('builds content props from the page contract', () => {
    expect(buildUserManagementContentProps(page)).toEqual({
      isMobile: true,
      canCreateUsers: true,
      isSubAdminUser: false,
      filteredUsers: [{ user_id: 'u-1' }],
      canManageUsers: true,
      canEditUserPolicy: true,
      canAssignGroups: true,
      canAssignTools: true,
      canResetPasswords: true,
      canResetPasswordForUser: page.canResetPasswordForUser,
      canToggleUserStatus: true,
      canDeleteUsers: true,
      statusUpdatingUserId: 'u-1',
      filters: { q: 'alice' },
      companies: [{ id: 1 }],
      departments: [{ id: 11 }],
      availableGroups: [{ group_id: 7 }],
      permissionGroupsLoading: true,
      permissionGroupsError: 'permission groups unavailable',
      groupedUsers: { QA: [] },
      setFilters: page.setFilters,
      handleLoadPermissionGroups: page.handleLoadPermissionGroups,
      handleOpenCreateModal: page.handleOpenCreateModal,
      handleOpenPolicyModal: page.handleOpenPolicyModal,
      handleAssignGroup: page.handleAssignGroup,
      handleAssignTool: page.handleAssignTool,
      handleOpenResetPassword: page.handleOpenResetPassword,
      handleDeleteUser: page.handleDeleteUser,
      handleToggleUserStatus: page.handleToggleUserStatus,
      handleResetFilters: page.handleResetFilters,
    });
  });

  it('builds modal props from the page contract', () => {
    expect(buildUserManagementModalProps(page)).toEqual({
      canCreateUsers: true,
      allUsers: [{ user_id: 'u-10', username: 'alice' }],
      showCreateModal: true,
      newUser: { username: 'alice' },
      createUserError: 'create error',
      availableGroups: [{ group_id: 7 }],
      availableTools: [{ group_id: 'paper_download' }],
      assignableTools: [{ group_id: 'drug_admin' }],
      permissionGroupsLoading: true,
      permissionGroupsError: 'permission groups unavailable',
      editingGroupUser: { user_id: 'u-1' },
      showGroupModal: true,
      selectedGroupIds: [7],
      editingToolUser: { user_id: 'u-2' },
      showToolModal: true,
      selectedToolIds: ['paper_download'],
      showResetPasswordModal: true,
      resetPasswordUser: { user_id: 'u-1' },
      resetPasswordValue: 'Password1',
      resetPasswordConfirm: 'Password1',
      resetPasswordSubmitting: true,
      resetPasswordError: 'reset error',
      showPolicyModal: true,
      policyUser: { user_id: 'u-1' },
      policySubmitting: true,
      policyError: 'policy error',
      policyForm: { user_type: 'normal' },
      statusUpdatingUserId: 'u-1',
      showDisableUserModal: true,
      disableTargetUser: { user_id: 'u-2' },
      disableMode: 'until',
      disableUntilDate: '2026-04-07',
      disableUserError: 'disable error',
      companies: [{ id: 1 }],
      departments: [{ id: 11 }],
      orgDirectoryError: 'org error',
      kbDirectoryNodes: [{ id: 'node-1' }],
      kbDirectoryLoading: true,
      kbDirectoryError: 'kb error',
      kbDirectoryCreateError: 'create kb error',
      kbDirectoryCreatingRoot: true,
      managedKbRootInvalid: true,
      subAdminOptions: [{ value: 'sub-1' }],
      policySubAdminOptions: [{ value: 'sub-2' }],
      handleChangePolicyForm: page.handleChangePolicyForm,
      setResetPasswordValue: page.setResetPasswordValue,
      setResetPasswordConfirm: page.setResetPasswordConfirm,
      handleCloseCreateModal: page.handleCloseCreateModal,
      setNewUserField: page.setNewUserField,
      toggleNewUserGroup: page.toggleNewUserGroup,
      toggleNewUserTool: page.toggleNewUserTool,
      handleCreateUser: page.handleCreateUser,
      handleCloseResetPassword: page.handleCloseResetPassword,
      handleSubmitResetPassword: page.handleSubmitResetPassword,
      handleClosePolicyModal: page.handleClosePolicyModal,
      handleTogglePolicyGroup: page.handleTogglePolicyGroup,
      handleTogglePolicyTool: page.handleTogglePolicyTool,
      handleSavePolicy: page.handleSavePolicy,
      handleCloseDisableUserModal: page.handleCloseDisableUserModal,
      handleChangeDisableMode: page.handleChangeDisableMode,
      handleChangeDisableUntilDate: page.handleChangeDisableUntilDate,
      handleConfirmDisableUser: page.handleConfirmDisableUser,
      handleCloseGroupModal: page.handleCloseGroupModal,
      toggleSelectedGroup: page.toggleSelectedGroup,
      handleSaveGroup: page.handleSaveGroup,
      handleCloseToolModal: page.handleCloseToolModal,
      toggleSelectedTool: page.toggleSelectedTool,
      handleSaveTool: page.handleSaveTool,
      handleCreateModalRootDirectory: page.handleCreateModalRootDirectory,
      handlePolicyRootDirectory: page.handlePolicyRootDirectory,
    });
  });
});
