export const buildUserManagementState = ({
  capabilities,
  dataState,
  createManagement,
  policyManagement,
  knowledgeDirectoryState,
  viewModel,
  actions,
  passwordReset,
  groupAssignment,
  toolAssignment,
  statusManagement,
  deletion,
}) => ({
  allUsers: dataState.allUsers,
  loading: dataState.loading,
  error: dataState.error,
  isSubAdminUser: capabilities.isSubAdminUser,
  canManageUsers: dataState.canManageUsers,
  canCreateUsers: capabilities.canCreateUsers,
  canEditUserPolicy: capabilities.canEditUserPolicy,
  canResetPasswords: capabilities.canResetPasswords,
  canToggleUserStatus: capabilities.canToggleUserStatus,
  canDeleteUsers: capabilities.canDeleteUsers,
  canAssignGroups: capabilities.canAssignGroups,
  canAssignTools: capabilities.canAssignTools,
  permissionGroupsLoading: dataState.permissionGroupsLoading,
  permissionGroupsError: dataState.permissionGroupsError,
  showCreateModal: createManagement.showCreateModal,
  newUser: createManagement.newUser,
  createUserError: createManagement.createUserError,
  filters: viewModel.filters,
  availableGroups: dataState.availableGroups,
  availableTools: dataState.availableTools,
  assignableTools: dataState.assignableTools,
  showPolicyModal: policyManagement.showPolicyModal,
  policyUser: policyManagement.policyUser,
  policySubmitting: actions.policySubmitting,
  policyError: policyManagement.policyError,
  policyForm: policyManagement.policyForm,
  companies: dataState.companies,
  departments: dataState.departments,
  orgDirectoryError: dataState.orgDirectoryError,
  kbDirectoryNodes: knowledgeDirectoryState.kbDirectoryNodes,
  kbDirectoryDisabledNodeIds: knowledgeDirectoryState.kbDirectoryDisabledNodeIds,
  kbDirectoryLoading: knowledgeDirectoryState.kbDirectoryLoading,
  kbDirectoryError: knowledgeDirectoryState.kbDirectoryError,
  kbDirectoryCreateError: knowledgeDirectoryState.kbDirectoryCreateError,
  kbDirectoryCreatingRoot: knowledgeDirectoryState.kbDirectoryCreatingRoot,
  managedKbRootInvalid: knowledgeDirectoryState.managedKbRootInvalid,
  filteredUsers: viewModel.filteredUsers,
  groupedUsers: viewModel.groupedUsers,
  subAdminOptions: viewModel.subAdminOptions,
  policySubAdminOptions: viewModel.policySubAdminOptions,
  setFilters: viewModel.setFilters,
  handleLoadPermissionGroups: dataState.fetchPermissionGroups,
  handleOpenCreateModal: actions.handleOpenCreateModal,
  handleCloseCreateModal: actions.handleCloseCreateModal,
  setNewUserField: actions.setNewUserField,
  toggleNewUserGroup: createManagement.toggleNewUserGroup,
  toggleNewUserTool: createManagement.toggleNewUserTool,
  handleCreateUser: actions.handleCreateUser,
  handleDeleteUser: deletion.handleDeleteUser,
  handleOpenPolicyModal: actions.handleOpenPolicyModal,
  handleClosePolicyModal: actions.handleClosePolicyModal,
  handleChangePolicyForm: actions.handleChangePolicyForm,
  handleTogglePolicyGroup: policyManagement.handleTogglePolicyGroup,
  handleTogglePolicyTool: policyManagement.handleTogglePolicyTool,
  handleSavePolicy: actions.handleSavePolicy,
  handleResetFilters: viewModel.handleResetFilters,
  handleCreateModalRootDirectory: knowledgeDirectoryState.handleCreateModalRootDirectory,
  handlePolicyRootDirectory: knowledgeDirectoryState.handlePolicyRootDirectory,
  ...passwordReset,
  ...groupAssignment,
  ...toolAssignment,
  ...statusManagement,
});
